version: "3"
services:
  bayarin.go:
    build: .
    command: gin --immediate --path /app go run main.go
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      - APP_PORT=80 
      - DB_HOST=bayarin.postgres
      - DB_PORT=5432
      - DB_USER=bayarin
      - DB_PASSWORD=bayarin
      - DB_NAME=bayarin
    depends_on:
      - bayarin.postgres
  bayarin.postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: bayarin
      POSTGRES_PASSWORD: bayarin
  bayarin.postgres.pgweb:
    image: sosedoff/pgweb:latest
    command: ["pgweb", "-s", "--bind=0.0.0.0", "--listen=8080", "--host=bayarin.postgres", "--user=bayarin", "--pass=bayarin", "--db=bayarin", "--ssl=disable"]
    restart: always
    ports:
      - "8070:8080"
    depends_on:
      - bayarin.postgres